on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: 
          submodules: 'true'

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_on_tmpfs: true

      - uses: rrbutani/use-nix-shell-action@59a52b2b9bbfe3cc0e7deb8f9059abe37a439edf # v1.1.0
        with:
          devShell: .#github_actions # use a special github actions shell

      - name: ensure all pre-commit hooks pass
        run: pre-commit run --all-files --show-diff-on-failure
